baseURL: "https://pinniped.dev/"
languageCode: "en-us"
title: "Pinniped"
theme: "pinniped"
params:
  twitter_url: "https://twitter.com/projectpinniped"
  github_url: "https://github.com/vmware-tanzu/pinniped"
  slack_url: "https://go.pinniped.dev/community/slack"
  community_url: "https://go.pinniped.dev/community"
  latest_version: v0.38.0
  latest_codegen_version: 1.31
pygmentsCodefences: true
pygmentsStyle: "pygments"
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: monokailight
    tabWidth: 4
related:
  includeNewer: true
  indices:
    - name: tags
      weight: 50
    - name: date
      weight: 50
  threshold: 0
  toLower: true
enableGitInfo: true
